version: '3.8'

services:
  backend:
    build: .
    container_name: tripare-backend
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
